// schema.dbml
// This is the source of truth for the database schema in this project.

// ------------------------ THIS IS JUST AN EXAMPLE ------------------------
// --- PLEASE DELETE THIS AND REPLACE IT WITH YOUR ACTUAL PROJECT SCHEMA ---

Table users {
  id integer
  username varchar
  role varchar
  created_at timestamp
}

Table posts {
  id integer [primary key]
  title varchar
  body text [note: 'Content of the post']
  user_id integer
  status post_status
  created_at timestamp
}

Enum post_status {
  draft
  published
  private [note: 'visible via URL only']
}

Ref: posts.user_id > users.id // many-to-one